---
# tasks file for user
- name: Stworzenie grupy
  group: 
    name: panda 
    state: present
 
- name: Stworzenie użytkownika i dodanie do grup
  user:
    name: panda
    shell: /bin/bash
    groups: 
      - panda
      - sudo
 
- name: kopia authorized_key z użytkownika vagrant o użytkownika panda
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"